<<<<<<< HEAD:todoproject/todo/migrations/0001_initial.py
# Generated by Django 5.2.6 on 2025-09-22 13:27
=======
# Generated by Django 5.2.6 on 2025-09-18 11:33
>>>>>>> 49a686e (💡 Todo 모델 생성):todo/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
<<<<<<< HEAD:todoproject/todo/migrations/0001_initial.py
                ('important', models.BooleanField(default=False)),
=======
>>>>>>> 49a686e (💡 Todo 모델 생성):todo/migrations/0001_initial.py
            ],
        ),
    ]
